---
resources:
- name: image
  type: docker-image
  source:
    repository: dolphm/ubuntu-latest-rust-nightly
- name: repo
  type: git
  source:
    uri: https://github.com/dolph/gerrit-query.git
    branch: master
- name: weekly
  type: time
  source:
    interval: 168h

jobs:
- name: build
  plan:
  - get: image
    trigger: true
  - get: repo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/ubuntu-latest-rust-nightly
      inputs:
      - name: repo
      run:
        path: repo/ci/build.sh
- name: release
  plan:
  - get: repo
    trigger: true
    passed: [build]
  - task: release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/ubuntu-latest-rust-nightly
      inputs:
      - name: repo
      run:
        path: repo/ci/release.sh
- name: archive
  plan:
  - get: weekly
    trigger: true
  - get: repo
    trigger: true
    passed: [build]
  - task: archive
    timeout: 168h
    serial: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: repo
      run:
        path: repo/ci/archive.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
